name:                hcc
version:             0.1.0.0
github:              "Nhlest/hcc"
license:             MIT
author:              "N`hlest"
maintainer:          "flutterlice@gmail.com"
copyright:           "2020 N`hlest"

extra-source-files:
- README.md

description:         HCC - the Haskell Cool Compiler

dependencies:
- base >= 4.7 && < 5
- containers
- parsec
- text
- mtl

executables:
  haskek-esque-exe:
    main:                Main.hs
    source-dirs:         src
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies: []